// In-memory one-time link codes for connecting a Helix account to a Telegram
// chat (plan.md Section 6, Module 1, secondary ingestion channel). A code is
// generated by an authenticated user (POST /auth/telegram/link-code) and
// redeemed by the bot when that user sends "/link <code>" in Telegram.
//
// Deliberately in-memory rather than a DB table: codes are short-lived (10
// min) and single-use, so losing them on a server restart is harmless — a
// user just requests a new one. Documented as a known hackathon-scale
// simplification; a horizontally-scaled deployment would need this in Redis
// or Postgres instead of process memory.
const CODE_TTL_MS = 10 * 60 * 1000;
const codes = new Map(); // code -> { userId, expiresAt }

function generateCode(userId) {
  const code = Math.random().toString(36).slice(2, 8).toUpperCase();
  codes.set(code, { userId, expiresAt: Date.now() + CODE_TTL_MS });
  return code;
}

function redeemCode(code) {
  const entry = codes.get(code?.toUpperCase());
  if (!entry) return null;
  codes.delete(code.toUpperCase());
  if (entry.expiresAt < Date.now()) return null;
  return entry.userId;
}

module.exports = { generateCode, redeemCode };
